services:

  app-1:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner

    image: landing-ai-seo:v1

    container_name: app-1

    restart: unless-stopped

    expose:
      - "3000"

    networks:
      - web_network

networks:
  web_network:
    external: true