services:

  app-3:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner

    image: landing-scaket:v1

    container_name: app-3

    restart: unless-stopped

    expose:
      - "3000"

    networks:
      - web_network

networks:
  web_network:
    external: true